name: "python"

on:
  push:
  merge_group:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'dev-requirements.txt'
    - name: Install Python dependencies
      run: pip install -r dev-requirements.txt
    - name: format python files
      run: |
        git ls-files "*.py" | xargs black --check
    - name: typecheck python files
      run: |
        git ls-files "*.py" | xargs pyright
